# Generated by Django 5.1.1 on 2024-09-11 10:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('flavour', models.CharField(choices=[('S/4H Private', 'S/4H Private'), ('S/4H Public', 'S/4H Public'), ('S/4 Cloud', 'S/4 Cloud'), ('S/4H OP', 'S/4H OP')], max_length=30)),
                ('sid', models.CharField(max_length=3)),
                ('estimated_clients', models.IntegerField()),
                ('delivered_clients', models.IntegerField(blank=True, null=True)),
                ('bfs', models.CharField(choices=[('Single', 'Single'), ('Multi', 'Multi')], max_length=10)),
                ('t_shirt_size', models.CharField(choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small')], max_length=10)),
                ('system_type', models.CharField(default='unknown', max_length=300)),
                ('hardware', models.CharField(choices=[('GCP', 'GCP'), ('Azure', 'Azure')], max_length=10)),
                ('setup', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('Reviewing eCS', 'Reviewing eCS'), ('Backup from source', 'Backup from source'), ('OAT Simulation', 'OAT Simulation'), ('Server Provisioning', 'Server Provisioning'), ('DB Installation', 'DB Installation'), ('Installation', 'Installation'), ('Post Installation', 'Post Installation'), ('Client 000 Customization', 'Client 000 Customization'), ('with SLC for TMS', 'with SLC for TMS'), ('Back from SLC', 'Back from SLC'), ('Higher client customization', 'Higher client customization'), ('Quality Checks', 'Quality Checks'), ('Handedover to PLO', 'Handedover to PLO')], max_length=50)),
                ('landscape', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('expected_delivery', models.DateField()),
                ('revised_delivery_date', models.DateField(blank=True, default=datetime.date(9999, 12, 31))),
                ('delivery_date', models.DateField(blank=True, default=datetime.date(9999, 12, 31))),
                ('delivery_delay_reason', models.CharField(blank=True, max_length=500)),
                ('servicenow', models.URLField(blank=True, max_length=800)),
                ('comments', models.CharField(max_length=400)),
                ('plo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plo_items', to='BuildTrackerApp.processor')),
                ('processor1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processor1_items', to='BuildTrackerApp.processor')),
                ('processor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processor2_items', to='BuildTrackerApp.processor')),
            ],
        ),
    ]
