# Generated by Django 5.1.1 on 2024-09-12 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildTrackerApp', '0002_alter_item_plo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='delivery_delay_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='revised_delivery_date',
            field=models.DateField(blank=True, default=datetime.date(9999, 12, 31), null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Reviewing eCS', 'Reviewing eCS'), ('Backup from source', 'Backup from source'), ('OAT Simulation', 'OAT Simulation'), ('Server Provisioning', 'Server Provisioning'), ('DB Installation', 'DB Installation'), ('Installation', 'Installation'), ('Post Installation', 'Post Installation'), ('Client 000 Customization', 'Client 000 Customization'), ('with SLC for TMS', 'with SLC for TMS'), ('Back from SLC', 'Back from SLC'), ('Higher client customization', 'Higher client customization'), ('Quality Checks', 'Quality Checks'), ('Handedover to PLO', 'Handedover to PLO')], max_length=50),
        ),
    ]
