# Generated by Django 5.1.1 on 2024-09-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildTrackerApp', '0003_alter_item_comments_alter_item_delivery_delay_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sid',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
