# Generated by Django 5.1.1 on 2024-09-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildTrackerApp', '0004_alter_item_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sid',
            field=models.CharField(max_length=3),
        ),
    ]
