# Generated by Django 5.1.1 on 2024-10-09 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildTrackerApp', '0006_alter_item_revised_delivery_date_alter_item_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=3)),
                ('clients', models.IntegerField()),
                ('bfs', models.CharField(choices=[('Single', 'Single'), ('Multi', 'Multi')], max_length=10)),
                ('system_description', models.CharField(max_length=300)),
                ('time_weeks', models.IntegerField()),
                ('landscape', models.CharField(max_length=300)),
                ('frontend', models.CharField(max_length=100)),
                ('parallel_processing', models.BooleanField(default=False)),
                ('cw_delivered', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=400, null=True)),
                ('cw_request_plo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_requests', to='BuildTrackerApp.plo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='BuildTrackerApp.item')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_requester', to='BuildTrackerApp.plo')),
            ],
        ),
    ]
