# Generated by Django 5.1.1 on 2024-10-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildTrackerApp', '0007_forecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='cw_request_plo',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
