# Generated by Django 5.1.1 on 2024-12-24 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildTrackerApp', '0010_alter_forecast_cw_delivered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='forecast',
            name='clients',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='cw_delivered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='cw_request_plo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='BuildTrackerApp.item'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='parallel_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_requester', to='BuildTrackerApp.plo'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='time_weeks',
            field=models.IntegerField(),
        ),
    ]
