# Generated by Django 5.1.1 on 2024-12-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuildTrackerApp', '0011_remove_forecast_assigned_to_alter_forecast_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sid',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
